# .changelogenrc.yml
packageFiles:
  - package.json

# Автообновление версии в package.json
bumpFiles:
  - package.json

# Какие типы коммитов включать
types:
  - type: feat
    section: "✨ Features"
    hidden: false
  - type: fix
    section: "🐛 Bug Fixes"
    hidden: false
  - type: docs
    section: "📚 Documentation"
    hidden: false
  - type: chore
    hidden: true
  - type: style
    hidden: true
  - type: refactor
    hidden: true
  - type: perf
    hidden: true
  - type: test
    hidden: true
  - type: build
    section: "📦 Build System"
    hidden: false
  - type: ci
    section: "⚙️ CI/CD"
    hidden: false
  - type: revert
    section: "⏪ Reverts"
    hidden: false

# Формат тега
tagPrefix: "v"

# Выходной файл
changelogFile: CHANGELOG.md

# Команда после обновления
afterBump:
  - "yarn lintfix" # Форматируем файлы после обновления версии
